services:
  postgres:
    image: postgres:latest
    container_name: v2-barbershop
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: barber
    ports:
      - 5432:5432
