services:
  postgres:
    image: postgres:latest
    container_name: barbershop
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: barber
    ports:
      - 5432:5432
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data:
