name: barber-app

services:
  pg:
    image: bitnami/postgresql:13.16.0
    container_name: fsw-v3-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=barber
